// Smoke test — replaces the stub generated by `flutter create`.
// (flutter create never overwrites existing files, so keeping this file in
// the repository prevents the MyApp placeholder from reappearing.)
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:leman_mail/presentation/screens/onboarding/onboarding_screen.dart';

void main() {
  testWidgets('l\'onboarding affiche la marque et le CTA', (tester) async {
    await tester.pumpWidget(const MaterialApp(home: OnboardingScreen()));

    expect(find.text('Leman Mail'), findsOneWidget);
    expect(find.text('Ajouter mon premier compte'), findsOneWidget);
  });
}
